### ISSUE TITLE
SpeechXf.startListening 报错

### ISSUE THREAD

**Issue by zhangweiwei0326** [shijia2118/speech_xf#3]
执行SpeechXf.startListening

E/AndroidRuntime(14556): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(14556): 	at com.example.speech_xf.SpeechXfPlugin$3.onError(SpeechXfPlugin.java:329)
E/AndroidRuntime(14556): 	at com.iflytek.cloud.c.a.f$c$a.handleMessage(SourceFile:57)
E/AndroidRuntime(14556): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(14556): 	at android.os.Looper.loop(Looper.java:219)

**Comment by zhangweiwei0326** [comment]
经过测试 SpeechXf.onSpeechResultListener 和 SpeechXf.onVolumeChanged 都无法设置成功 
Flutter (Channel stable, 3.16.7

**Comment by CarpOrange** [comment]
EventSink.success这个我手动改源码了，直接判空。
